// Spark air conditioning catalogue — Worcester Bosch Climate range.
// Specs from the Worcester Bosch Climate installer guide. PRICES ARE PLACEHOLDERS — confirm before launch.
export const PRODUCTS = [
  { id: 'climate-26', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 3200i 2.6kW', badge: '', img: 'assets/aircon-3200i-bedroom.jpg', rooms: 'Bedrooms & small rooms up to 20m²', price: 1995, priceNote: 'supplied & installed · 0% VAT', body: 'The smallest unit in the Climate 3200i range — quiet enough for bedrooms at 22 dB(A), with 2.9kW of heating output in winter and a washable filter plus built-in ionizer for cleaner air.', specs: [ ['Cooling capacity','2.6kW'], ['Heating output','2.9kW'], ['Cooling efficiency','SEER 7.4 · A++'], ['Heating efficiency','SCOP 4.1 · A+'], ['Indoor noise','from 20 dB(A)'], ['Operating range','−15°C to 50°C'], ['Refrigerant','R32'], ['Control','Remote + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1 day'] ] },
  { id: 'climate-35', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 3200i 3.5kW', badge: 'Bestseller', img: 'assets/aircon-install.jpg', rooms: 'Living rooms & spaces of 20–30m²', price: 2295, priceNote: 'supplied & installed · 0% VAT', body: 'Our most popular unit — the right size for most UK living rooms, delivering around 3.8kW of warmth in winter with an SCOP of 4.2, plus dehumidifying and a built-in ionizer.', specs: [ ['Cooling capacity','3.5kW'], ['Heating output','3.8kW'], ['Cooling efficiency','SEER 7.0 · A++'], ['Heating efficiency','SCOP 4.2 · A+'], ['Indoor noise','from 21 dB(A)'], ['Operating range','−15°C to 50°C'], ['Refrigerant','R32'], ['Control','Remote + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1 day'] ] },
  { id: 'climate-53', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 3200i 5.3kW', badge: '', img: 'assets/aircon-engineer.jpg', rooms: 'Large or open-plan rooms of 30–45m²', price: 2795, priceNote: 'supplied & installed · 0% VAT', body: 'For big, open-plan spaces and rooms with lots of glazing — around 5.6kW of heating output with the same all-in-one cooling, heating and dehumidifying.', specs: [ ['Cooling capacity','5.3kW'], ['Heating output','5.6kW'], ['Cooling efficiency','SEER 7.0 · A++'], ['Heating efficiency','SCOP 4.0 · A+'], ['Indoor noise','from 20 dB(A)'], ['Operating range','−15°C to 50°C'], ['Refrigerant','R32'], ['Control','Remote + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1 day'] ] },
  { id: 'climate-70', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 3200i 7.0kW', badge: '', img: 'assets/aircon-outdoor-unit.jpg', fit: 'contain', rooms: 'Very large spaces of 45–60m²', price: 3295, priceNote: 'supplied & installed · 0% VAT', body: 'The largest single-room unit in the 3200i range — for very large or hard-to-heat spaces, with around 7.3kW of warmth in winter.', specs: [ ['Cooling capacity','7.0kW'], ['Heating output','7.3kW'], ['Cooling efficiency','SEER 6.4 · A++'], ['Heating efficiency','SCOP 4.0 · A+'], ['Indoor noise','from 21 dB(A)'], ['Operating range','−15°C to 50°C'], ['Refrigerant','R32'], ['Control','Remote + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1 day'] ] },
  { id: 'climate-7000i-34', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 7000i 3.4kW', badge: 'Premium', img: 'assets/aircon-7000i-black-living.jpg', rooms: 'Living rooms of 20–30m² · white or black', price: 2795, priceNote: 'supplied & installed · 0% VAT', body: 'The smartest and sleekest unit Worcester Bosch make, in white or black. Industry-leading efficiency (SEER 9.7, SCOP 5.1, A+++ both ways), a bio filter and advanced ionizer, energy monitoring and smart-home control included as standard.', specs: [ ['Cooling capacity','3.4kW'], ['Heating output','4.1kW'], ['Cooling efficiency','SEER 9.7 · A+++'], ['Heating efficiency','SCOP 5.1 · A+++'], ['Indoor noise','from 24 dB(A)'], ['Heats down to','−30°C outside'], ['Refrigerant','R32'], ['Control','Wi-Fi + voice control included'], ['Finish','White or black'], ['Guarantee','Up to 7 years'], ['Typical install','1 day'] ] },
  { id: 'climate-7000i-50', kind: 'unit', brand: 'Worcester Bosch', name: 'Climate 7000i 5.0kW', badge: '', img: 'assets/aircon-7000i-dining.jpg', rooms: 'Large rooms of 30–45m² · white or black', price: 3495, priceNote: 'supplied & installed · 0% VAT', body: 'The larger Climate 7000i, in white or black — A+++ heating with 5.6kW of output down to −30°C outside, plus bio filter, advanced ionizer and energy monitoring as standard.', specs: [ ['Cooling capacity','5.0kW'], ['Heating output','5.6kW'], ['Cooling efficiency','SEER 8.5 · A++'], ['Heating efficiency','SCOP 4.6 · A+++'], ['Indoor noise','from 28 dB(A)'], ['Heats down to','−30°C outside'], ['Refrigerant','R32'], ['Control','Wi-Fi + voice control included'], ['Finish','White or black'], ['Guarantee','Up to 7 years'], ['Typical install','1 day'] ] },
  { id: 'multi-2', kind: 'multi', brand: 'Worcester Bosch', name: 'Climate 5000 M ×2 rooms', badge: '', img: 'assets/aircon-cassette.jpg', rooms: 'Two rooms from a single outdoor unit', price: 4495, priceNote: 'supplied & installed · 0% VAT', body: 'Two indoor units — typically a living room and main bedroom — run from one Climate 5000 M outdoor unit, each room controlled independently.', specs: [ ['Indoor units','2, individually controlled'], ['Outdoor units','1'], ['System capacity','4.1–5.3kW'], ['Cooling efficiency','SEER up to 6.8 · A++'], ['Heating efficiency','SCOP 4.0 · A+'], ['Indoor noise','from 22 dB(A)'], ['Refrigerant','R32'], ['Control','Remotes + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1–2 days'] ] },
  { id: 'multi-3', kind: 'multi', brand: 'Worcester Bosch', name: 'Climate 5000 M ×3 rooms', badge: '', img: 'assets/aircon-app.jpg', rooms: 'Three rooms from a single outdoor unit', price: 5995, priceNote: 'supplied & installed · 0% VAT', body: 'Whole-home comfort — three indoor units run from one Climate 5000 M outdoor unit (the range connects up to five), each room set independently.', specs: [ ['Indoor units','3, individually controlled'], ['Outdoor units','1'], ['System capacity','6.2–7.9kW'], ['Cooling efficiency','SEER up to 6.5 · A++'], ['Heating efficiency','SCOP 4.0 · A+'], ['Indoor noise','from 22 dB(A)'], ['Refrigerant','R32'], ['Control','Remotes + HomeCom Easy app*'], ['Guarantee','Up to 5 years'], ['Typical install','1–2 days'] ] },
  { id: 'svc-survey', kind: 'service', brand: 'Spark', name: '£49 home survey', badge: '', img: 'assets/aircon-engineer.jpg', rooms: 'An engineer measures your heat load properly and checks grant eligibility', price: 49, priceNote: 'incl. 20% VAT · deducted from your installation', body: 'An engineer visits, measures the heat load of your rooms properly, checks your Boiler Upgrade Scheme eligibility and confirms your exact fixed price. The £49 comes off your installation.', specs: [ ['Visit length','around 1 hour'], ['Includes','room-by-room heat-load calculation'], ['Grant check','Boiler Upgrade Scheme eligibility'], ['Credit','£49 deducted from installation'] ] },
  { id: 'svc-service', kind: 'service', brand: 'Spark', name: 'Annual service', badge: '', img: 'assets/aircon-install.jpg', rooms: 'Keep your system efficient and your warranty intact', price: 120, priceNote: 'incl. 20% VAT', body: 'A yearly clean, refrigerant and performance check that keeps your system at peak efficiency and protects your warranty.', specs: [ ['Visit length','around 1 hour'], ['Includes','filter clean, refrigerant & performance check'], ['Keeps','manufacturer warranty valid'] ] },
];
// *HomeCom Easy app control on the 3200i / 5000 M requires the optional Gateway G10-3 accessory.
export const gbp = (n) => '£' + n.toLocaleString('en-GB');
const KEY = 'sparkAirconCart';
export function getCart() { try { return JSON.parse(localStorage.getItem(KEY)) || []; } catch (e) { return []; } }
export function setCart(items) { localStorage.setItem(KEY, JSON.stringify(items.filter(i => i.qty > 0))); }
export function addToCart(id, qty) { const c = getCart(); const ln = c.find(i => i.id === id); if (ln) ln.qty += (qty || 1); else c.push({ id: id, qty: qty || 1 }); setCart(c); return c; }
export function cartStats() { const c = getCart(); let n = 0, t = 0; c.forEach(i => { const p = PRODUCTS.find(p => p.id === i.id); if (p) { n += i.qty; t += p.price * i.qty; } }); return { count: n, total: t }; }
